name: CI

on:
  schedule:
    - cron: '0 6 * * *'  # This runs the workflow every day at 6 AM.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "" >> README.md
          git config user.name "your_name"
          git config user.email "your_email@email.com"
          git add README.md
          git commit -m "Always green"
          git push
